name: ShowAPI
version: ${project.version}
main: nl.sbdeveloper.showapi.ShowAPIPlugin
api-version: 1.13
authors: [SBDeveloper]
description: Make perfect shows with this API!
website: https://sbdplugins.nl
commands:
  mctpshow:
    description: Het show command!
permissions:
  mctp.show:
    description: De permissie voor /mctpshow