name: ShowControl
version: ${project.version}
main: tech.sbdevelopment.showcontrol.ShowControlPlugin
api-version: 1.13
authors: [SBDeveloper]
description: Create shows easily using this plugin!
website: https://sbdevelopment.tech