name: ShowControl
version: ${project.version}
main: nl.sbdeveloper.showcontrol.ShowControlPlugin
api-version: 1.13
authors: [SBDeveloper]
description: Make perfect shows with this API!
website: https://sbdevelopment.tech